### ISSUE TITLE
new device request

### ISSUE THREAD

**Issue by Ankitdas-1234** [AXP-OS/issue-tracker#17] opened 2024-09-18 18:51 UTC
### Device vendor

Nokia

### Device model

3.1 

### Device codename

ES2

### LineageOS device tree and/or WIKI page

https://github.com/nokia-mt6750/android_device_nokia_ES2

### Supported by DivestOS already?

no (see Notes-1)

### Prepared to support?

- [X] yes, I've joined

**Comment by steadfasterX** [comment] 2024-09-18 19:04
Pls do not open new issues for the same device. There is a comment box if u want to add smth.

Closed as duplicate of #16

**Closed** 2024-09-18 19:04 UTC
Labels: device-request
